### ISSUE TITLE
Error invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by srisvk055** [redhat-cop/keepalived-operator#132]
When the keepalived operator is installer, operations of the keepalived is working as expected but the operator pod CrashLoopBackOff with the following error. 

Env: Openshift 
OCP Version: 4.14
Keepalived version: 1.5.4

Logs from the keepalived-operator-controller-manager/manager: 

E1030 11:42:48.659151 1 runtime.go:79] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 498 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x153f420?, 0x2408e80})
/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/runtime/runtime.go:75 +0x99
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x100c00086ca70?})
/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/runtime/runtime.go:49 +0x75
panic({0x153f420, 0x2408e80})
/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x207
github.com/go-logr/logr.Logger.Error({{0x0?, 0x0?}, 0xc0009bf9f8?}, {0x1935a20, 0xc00199a650}, {0x172bd2b, 0x25}, {0xc0018eab00, 0x4, 0x4})
/home/runner/go/pkg/mod/github.com/go-logr/logr@v1.2.0/logr.go:265 +0x80
github.com/redhat-cop/keepalived-operator/controllers.(*enqueueRequestForReferredKeepAlivedGroup).Create(0xc0005fa150, {{0x19577f0?, 0xc0009bf9f8?}}, {0x1951250, 0xc0004e1900})
/home/runner/work/keepalived-operator/keepalived-operator/controllers/keepalivedgroup_controller.go:428 +0x174
sigs.k8s.io/controller-runtime/pkg/source/internal.EventHandler.OnAdd({{0x194c470, 0xc0005fa150}, {0x1951250, 0xc0004e1900}, {0xc000076e00, 0x1, 0x1}}, {0x16e1b60?, 0xc0009bf9f8})
/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.2/pkg/source/internal/eventsource.go:63 +0x23c
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
/home/runner/go/pkg/mod/k8s.io/client-go@v0.24.2/tools/cache/shared_informer.go:818 +0xaf
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x10000000011?)
/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/wait/wait.go:155 +0x3e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000492738?, {0x1938440, 0xc000952150}, 0x1, 0xc001a60000)
/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/wait/wait.go:156 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0004927a0?, 0x3b9aca00, 0x0, 0x0?, 0xc000044a20?)
/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(...)
/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/wait/wait.go:90
k8s.io/client-go/tools/cache.(*processorListener).run(0xc001606080?)
/home/runner/go/pkg/mod/k8s.io/client-go@v0.24.2/tools/cache/shared_informer.go:812 +0x6b
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/wait/wait.go:73 +0x5a
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/wait/wait.go:71 +0x85
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x75b580]

**Comment by srisvk055** [comment]
This above error exactly happens when the keepalived operator provisions the VIP, until then the keepalived-operator-controller-manager/manager is healthy. 

https://github.com/redhat-cop/keepalived-operator/blob/master/Ingress-how-to.md

**Comment by StrikeZW** [comment]
> This above error exactly happens when the keepalived operator provisions the VIP, until then the keepalived-operator-controller-manager/manager is healthy.
> 
> https://github.com/redhat-cop/keepalived-operator/blob/master/Ingress-how-to.md

Did you ever resolved this? Any hints would be nice
